apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: app
    image: unbuntu
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done;"]
    volumeMounts:
    - name: persistant-storage
      mountPath: /data 
  volumes: 
  - name: persistant-storage
    persistentVolumeClaim:
      claimName: pvc-dynamic

